[package]
name = "axo-project"
description = "project detection logic for various axo.dev applications"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/axodotdev/cargo-dist"
exclude = [
  "book/*",
  "src/snapshots/*",
  "src/tests/",
  "tests/",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "axo-project"
required-features = ["cli"]

[features]
default = ["cli"]
cli = ["cargo-projects", "npm-projects"]
cargo-projects = ["guppy"]
npm-projects = ["oro-common"]

[dependencies]
camino = "1.1.4"
console = "0.15.5"
miette = "5.6.0"
guppy = { version = "0.15.2", optional = true }
tracing = "0.1.37"
oro-common = { version = "0.3.11", optional = true }
serde_json = "1.0.94"
serde = "1.0.158"

